[2021-12-06 09:06:08,040] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Download_Stock_Price.save_to_database manual__2021-12-06T09:06:00.536637+00:00 [queued]>
[2021-12-06 09:06:08,055] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Download_Stock_Price.save_to_database manual__2021-12-06T09:06:00.536637+00:00 [queued]>
[2021-12-06 09:06:08,055] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-06 09:06:08,056] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-12-06 09:06:08,056] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-06 09:06:08,081] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): save_to_database> on 2021-12-06 09:06:00.536637+00:00
[2021-12-06 09:06:08,088] {standard_task_runner.py:52} INFO - Started process 3024 to run task
[2021-12-06 09:06:08,094] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Download_Stock_Price', 'save_to_database', 'manual__2021-12-06T09:06:00.536637+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/download_stick_price.py', '--cfg-path', '/tmp/tmpb_zqsoz2', '--error-file', '/tmp/tmpmyi92q30']
[2021-12-06 09:06:08,095] {standard_task_runner.py:77} INFO - Job 41: Subtask save_to_database
[2021-12-06 09:06:08,164] {logging_mixin.py:109} INFO - Running <TaskInstance: Download_Stock_Price.save_to_database manual__2021-12-06T09:06:00.536637+00:00 [running]> on host 48b97d3f8617
[2021-12-06 09:06:08,243] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=tlzmkm@gmail.com
AIRFLOW_CTX_DAG_OWNER=tl
AIRFLOW_CTX_DAG_ID=Download_Stock_Price
AIRFLOW_CTX_TASK_ID=save_to_database
AIRFLOW_CTX_EXECUTION_DATE=2021-12-06T09:06:00.536637+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-06T09:06:00.536637+00:00
[2021-12-06 09:06:08,256] {logging_mixin.py:109} INFO - received tickers: ['MSFT', 'GE']
[2021-12-06 09:06:08,268] {base.py:79} INFO - Using connection to: id: demodb. Host: postgres, Port: 5432, Schema: demodb, Login: ***, Password: ***, extra: {}
[2021-12-06 09:06:08,423] {logging_mixin.py:109} INFO - MSFT length=9007   ['MSFT', '1986-03-14', '0.06137834941070945', '0.06466690297385626', '0.06137834941070945', '0.0635702982544899']
[2021-12-06 09:06:12,544] {logging_mixin.py:109} INFO - GE length=15085   ['GE', '1962-01-03', '1.0075934424202766', '1.0075934424202766', '0.9991262415036191', '1.0025131702423096']
[2021-12-06 09:06:17,771] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_stick_price.py", line 90, in save_to_psql_stage
    mycursor.commit()
AttributeError: 'psycopg2.extensions.cursor' object has no attribute 'commit'
[2021-12-06 09:06:17,789] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=Download_Stock_Price, task_id=save_to_database, execution_date=20211206T090600, start_date=20211206T090608, end_date=20211206T090617
[2021-12-06 09:06:17,804] {standard_task_runner.py:91} ERROR - Failed to execute job 41 for task save_to_database
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_stick_price.py", line 90, in save_to_psql_stage
    mycursor.commit()
AttributeError: 'psycopg2.extensions.cursor' object has no attribute 'commit'
[2021-12-06 09:06:17,856] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-06 09:06:17,883] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
